### PR TITLE
Overhaul infrastructure

### LINKED ISSUE #4: Fails to build with GHC 8.10.7
Your project looks pretty cool. Would you like to bring it up to date with current GHC versions? The errors I get look like there's been changes to Template Haskell types. The first one is

```
src/Categorical/Dual.hs:229:23: error:
    • Couldn't match type ‘Exp’ with ‘Maybe Exp’
      Expected type: ExceptT (Either Type Exp) Q [Maybe Exp]
        Actual type: ExceptT (Either Type Exp) Q [Exp]
    • In the second argument of ‘(<$>)’, namely
        ‘traverse (dualExp' db) es’
      In the expression: TupE <$> traverse (dualExp' db) es
      In a case alternative:
          TupE es -> TupE <$> traverse (dualExp' db) es
    |
229 |   TupE es -> TupE <$> traverse (dualExp' db) es -- FIXME: Doesn’t seem right.
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^
```

### LINKED ISSUE #6: Fails to build with ghc-9.10.1
```
dualizer                     > build (lib) with ghc-9.10.1
Preprocessing library for dualizer-0.1.0.1...
Building library for dualizer-0.1.0.1...
[1 of 5] Compiling Categorical.Dual
/home/andreas/stackage/stackage/tmp.mLkv/dualizer-0.1.0.1/src/Categorical/Dual.hs:238:3: error: [GHC-27346]
    • The data constructor ‘DoE’ should have 2 arguments, but has been given 1
    • In the pattern: DoE ss
      In a \case alternative:
          DoE ss -> DoE <$> traverse (dualStmt' db) ss
      In the expression:
        \case           
          v@(VarE n)    
            -> ExceptT . recover (pure $ pure v) . runExceptT
                 $ dualExpName db n
          ConE n -> dualExpName db n
          l@(LitE _) -> pure l
          AppE a b -> AppE <$> dualExp' db a <*> dualExp' db b
          InfixE a o b  
            -> InfixE <$> traverse (dualExp' db) a <*> dualExp' db o
                 <*> traverse (dualExp' db) b
          UInfixE a o b 
            -> UInfixE <$> dualExp' db a <*> dualExp' db o <*> dualExp' db b
          ParensE e -> ParensE <$> dualExp' db e
          LamE p e -> LamE p <$> dualExp' db e
          LamCaseE matches -> LamCaseE <$> traverse (dualMatch' db) matches
          TupE es -> TupE <$> traverse (dualExp' db) es
          UnboxedTupE es -> UnboxedTupE <$> traverse (dualExp' db) es
          CondE t c a   
            -> CondE <$> dualExp' db t <*> dualExp' db c <*> dualExp' db a
          MultiIfE cases
            -> MultiIfE 
                 <$> traverse (bisequence . (dualGuard' db *** dualExp' db)) cases
          LetE ds e -> LetE <$> traverse (dualDec' db) ds <*> dualExp' db e
          CaseE e ms    
            -> CaseE <$> dualExp' db e <*> traverse (dualMatch' db) ms
          DoE ss -> DoE <$> traverse (dualStmt' db) ss
          CompE ss -> CompE <$> traverse (dualStmt' db) ss
          ArithSeqE r -> pure $ ArithSeqE r
          ListE es -> ListE <$> traverse (dualExp' db) es
          SigE e t      
            -> SigE <$> dualExp' db e
                 <*> withExceptT Left (dualType' (_dualTypes db) t)
          e@(RecConE _ _) -> throwE $ Right e
          e@(RecUpdE _ _) -> throwE $ Right e
          StaticE e -> StaticE <$> dualExp' db e
          UnboundVarE n -> pure $ UnboundVarE n
    |                   
238 |   DoE ss -> DoE <$> traverse (dualStmt' db) ss
    |   ^^^^^^          
                        
/home/andreas/stackage/stackage/tmp.mLkv/dualizer-0.1.0.1/src/Categorical/Dual.hs:396:19: error: [GHC-27346]
    • The data constructor ‘TySynEqn’ should have 3 arguments, but has been given 2
    • In the pattern: TySynEqn ts t
      In an equation for ‘dualTySynEqn'’:
          dualTySynEqn' db (TySynEqn ts t)
            = TySynEqn <$> traverse (dualType' db) ts <*> dualType' db t
    |                   
396 | dualTySynEqn' db (TySynEqn ts t) =
    | 
```

### PR DESCRIPTION
**Pull request by sellout**
This adopts Flaky and the rest of my current infrastructure, to keep things up-to-date and tested more easily.

This now supports GHC 8.6–9.10.

Fixes #4 and fixes #6.

### CODE REVIEW

**Comment by sellout** [comment]
The remaining failure is a remnant of garnix-io/issues#119.
