### ISSUE TITLE
Fails to build with GHC 8.10.7

### ISSUE THREAD

**Issue by johannes-riecken** [sellout/dualizer#4]
Your project looks pretty cool. Would you like to bring it up to date with current GHC versions? The errors I get look like there's been changes to Template Haskell types. The first one is

```
src/Categorical/Dual.hs:229:23: error:
    • Couldn't match type ‘Exp’ with ‘Maybe Exp’
      Expected type: ExceptT (Either Type Exp) Q [Maybe Exp]
        Actual type: ExceptT (Either Type Exp) Q [Exp]
    • In the second argument of ‘(<$>)’, namely
        ‘traverse (dualExp' db) es’
      In the expression: TupE <$> traverse (dualExp' db) es
      In a case alternative:
          TupE es -> TupE <$> traverse (dualExp' db) es
    |
229 |   TupE es -> TupE <$> traverse (dualExp' db) es -- FIXME: Doesn’t seem right.
    |                       ^^^^^^^^^^^^^^^^^^^^^^^^^
```
